"""
================================================================================
TRAIN KNN MODEL
================================================================================

Purpose: Script to train and save the KNN sport recommender model.
Handles the training pipeline: load data from database, train the model, and
save it to disk for production use.
================================================================================
"""

from ml.recommender import KNNSportRecommender
from utils.db import get_ml_training_data_cli

# =============================================================================
# MODEL TRAINING
# =============================================================================
# PURPOSE: Train and save the KNN recommender model

def train_and_save_model():
    """Train and save the KNN recommender model.
    
    Workflow:
    1. Load training data from database
    2. Create KNNSportRecommender instance
    3. Train model with load_and_train()
    4. Save to ml/models/knn_recommender.joblib
        
    Raises:
        ValueError: If training data cannot be loaded from database.
    """
    print("\n" + "="*60)
    print("KNN SPORT RECOMMENDER - MODEL TRAINING")
    print("="*60 + "\n")
    
    # Load training data from database via client layer
    print("Loading training data from database...")
    training_data = get_ml_training_data_cli()
    
    # Create recommender instance and execute training
    # WHY: n_neighbors=10 finds 10 similar sports for recommendations
    # The load_and_train() method contains the core training logic (preprocessing, scaling, fitting)
    recommender = KNNSportRecommender(n_neighbors=10)
    recommender.load_and_train(training_data)
    
    # Save the model (prepare for production deployment)
    # WHY: Persist complete trained model bundle to disk for instant loading in production Streamlit app
    print("\n" + "="*60)
    from pathlib import Path
    recommender.save_model(str(Path("ml/models/knn_recommender.joblib")))
    print("✅ KNN ML Model ready for production!")
    print("="*60 + "\n")

if __name__ == "__main__":
    train_and_save_model()

# Parts of this codebase were developed with the assistance of AI-based tools (Cursor and Github Copilot)
# All outputs generated by such systems were reviewed, validated, and modified by the author.