-- =====================================================================
-- UnisportAI - Database Schema (Tables + Views)
-- =====================================================================
-- Schema definition for the UnisportAI application on Supabase.
-- Defines the tables and views used by the Streamlit app and
-- the ML components.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Schema and prerequisites
-- ---------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;

-- Enable pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------
-- 1. Core user table
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.users (
    id                      uuid PRIMARY KEY,
    email                   text UNIQUE,
    sub                     text UNIQUE,
    name                    text,
    picture                 text,

    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz DEFAULT now(),
    last_login              timestamptz,

    is_public               boolean DEFAULT false,
    bio                     text,

    preferences             jsonb DEFAULT '{}'::jsonb,

    -- Preferences stored as simple text arrays for clarity
    preferred_intensities   text[],
    preferred_focus         text[],
    preferred_settings      text[],
    favorite_location_names text[],
    preferred_weekdays      text[]
);

-- ---------------------------------------------------------------------
-- 2. Sport offers and related tables
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sportangebote (
    href        text PRIMARY KEY,
    name        text NOT NULL,
    description text,

    -- Intensity as plain text (expected values: 'low', 'moderate', 'high')
    intensity   text,

    -- Focus and setting as simple tag lists
    focus       text[],
    setting     text[],

    icon        text,
    image_url   text
);

CREATE TABLE IF NOT EXISTS public.sportkurse (
    kursnr        text PRIMARY KEY,
    details       text,
    preis         text,
    buchung       text,
    offer_href    text,
    zeitraum_href text,

    CONSTRAINT sportkurse_offer_href_fkey
        FOREIGN KEY (offer_href)
        REFERENCES public.sportangebote(href)
);

CREATE TABLE IF NOT EXISTS public.trainer (
    name       text PRIMARY KEY,
    rating     integer NOT NULL DEFAULT 3
               CHECK (rating >= 1 AND rating <= 5),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.unisport_locations (
    name           text PRIMARY KEY,
    lat            double precision,
    lng            double precision,
    ort_href       text,
    spid           text,

    -- Indoor / outdoor classification as plain text
    -- Typical values: 'indoor', 'outdoor', 'mixed', 'unknown'
    indoor_outdoor text
);

CREATE TABLE IF NOT EXISTS public.kurs_termine (
    kursnr        text NOT NULL,
    ort_href      text,
    canceled      boolean NOT NULL DEFAULT false,
    location_name text,
    start_time    timestamptz NOT NULL,
    end_time      timestamptz,

    CONSTRAINT kurs_termine_pkey
        PRIMARY KEY (kursnr, start_time),

    CONSTRAINT kurs_termine_kursnr_fkey
        FOREIGN KEY (kursnr)
        REFERENCES public.sportkurse(kursnr),

    CONSTRAINT kurs_termine_location_fk
        FOREIGN KEY (location_name)
        REFERENCES public.unisport_locations(name)
);

CREATE TABLE IF NOT EXISTS public.kurs_trainer (
    kursnr       text NOT NULL,
    trainer_name text NOT NULL,

    CONSTRAINT kurs_trainer_pkey
        PRIMARY KEY (kursnr, trainer_name),

    CONSTRAINT kurs_trainer_kursnr_fkey
        FOREIGN KEY (kursnr)
        REFERENCES public.sportkurse(kursnr),

    CONSTRAINT kurs_trainer_trainer_name_fkey
        FOREIGN KEY (trainer_name)
        REFERENCES public.trainer(name)
);

-- ---------------------------------------------------------------------
-- 3. Ratings (sports and trainers)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sportangebote_user_ratings (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           uuid NOT NULL,
    sportangebot_href text NOT NULL,
    rating            integer NOT NULL
                       CHECK (rating >= 1 AND rating <= 5),
    comment           text,
    created_at        timestamptz DEFAULT now(),
    updated_at        timestamptz DEFAULT now(),

    CONSTRAINT sportangebote_user_ratings_user_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.users(id),

    CONSTRAINT sportangebote_user_ratings_sportangebot_href_fkey
        FOREIGN KEY (sportangebot_href)
        REFERENCES public.sportangebote(href)
);

CREATE TABLE IF NOT EXISTS public.trainer_user_ratings (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      uuid NOT NULL,
    trainer_name text NOT NULL,
    rating       integer NOT NULL
                 CHECK (rating >= 1 AND rating <= 5),
    comment      text,
    created_at   timestamptz DEFAULT now(),
    updated_at   timestamptz DEFAULT now(),

    CONSTRAINT trainer_user_ratings_user_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.users(id),

    CONSTRAINT trainer_user_ratings_trainer_name_fkey
        FOREIGN KEY (trainer_name)
        REFERENCES public.trainer(name)
);

-- ---------------------------------------------------------------------
-- 4. Favorites and social graph
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_favorites (
    id                uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id           uuid NOT NULL,
    sportangebot_href text NOT NULL,
    created_at        timestamptz DEFAULT now(),

    CONSTRAINT user_favorites_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.users(id),

    CONSTRAINT user_favorites_sportangebot_href_fkey
        FOREIGN KEY (sportangebot_href)
        REFERENCES public.sportangebote(href)
);

CREATE TABLE IF NOT EXISTS public.friend_requests (
    id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    requester_id uuid NOT NULL,
    addressee_id uuid NOT NULL,
    status       text NOT NULL DEFAULT 'pending',
    created_at   timestamptz DEFAULT now(),
    updated_at   timestamptz DEFAULT now(),

    CONSTRAINT friend_requests_requester_id_fkey
        FOREIGN KEY (requester_id)
        REFERENCES public.users(id),

    CONSTRAINT friend_requests_addressee_id_fkey
        FOREIGN KEY (addressee_id)
        REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.user_friends (
    id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    requester_id uuid NOT NULL,
    addressee_id uuid NOT NULL,
    created_at   timestamptz DEFAULT now(),

    CONSTRAINT user_friends_requester_id_fkey
        FOREIGN KEY (requester_id)
        REFERENCES public.users(id),

    CONSTRAINT user_friends_addressee_id_fkey
        FOREIGN KEY (addressee_id)
        REFERENCES public.users(id)
);

-- ---------------------------------------------------------------------
-- 5. ETL bookkeeping
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.etl_runs (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ran_at    timestamptz NOT NULL DEFAULT now(),

    -- Component name stored as free text for simplicity
    component text NOT NULL
);

-- =====================================================================
-- 6. Views (same structure as in main schema, but using simple types)
-- =====================================================================

-- 6.1 ml_training_data

CREATE OR REPLACE VIEW public.ml_training_data AS
SELECT
    sa.href AS href,
    sa.name AS "Angebot",

    CASE WHEN 'balance'     = ANY (sa.focus) THEN 1.0 ELSE 0.0 END AS balance,
    CASE WHEN 'flexibility' = ANY (sa.focus) THEN 1.0 ELSE 0.0 END AS flexibility,
    CASE WHEN 'coordination'= ANY (sa.focus) THEN 1.0 ELSE 0.0 END AS coordination,
    CASE WHEN 'relaxation'  = ANY (sa.focus) THEN 1.0 ELSE 0.0 END AS relaxation,
    CASE WHEN 'strength'    = ANY (sa.focus) THEN 1.0 ELSE 0.0 END AS strength,
    CASE WHEN 'endurance'   = ANY (sa.focus) THEN 1.0 ELSE 0.0 END AS endurance,
    CASE WHEN 'longevity'   = ANY (sa.focus) THEN 1.0 ELSE 0.0 END AS longevity,

    CASE sa.intensity
        WHEN 'low'      THEN 0.33
        WHEN 'moderate' THEN 0.67
        WHEN 'high'     THEN 1.0
        ELSE 0.0
    END AS intensity,

    CASE WHEN 'team'        = ANY (sa.setting) THEN 1.0 ELSE 0.0 END AS setting_team,
    CASE WHEN 'fun'         = ANY (sa.setting) THEN 1.0 ELSE 0.0 END AS setting_fun,
    CASE WHEN 'duo'         = ANY (sa.setting) THEN 1.0 ELSE 0.0 END AS setting_duo,
    CASE WHEN 'solo'        = ANY (sa.setting) THEN 1.0 ELSE 0.0 END AS setting_solo,
    CASE WHEN 'competitive' = ANY (sa.setting) THEN 1.0 ELSE 0.0 END AS setting_competitive

FROM public.sportangebote sa;

-- 6.2 vw_offers_complete

CREATE OR REPLACE VIEW public.vw_offers_complete AS
WITH ratings AS (
    SELECT
        r.sportangebot_href AS href,
        AVG(r.rating)::numeric(4,2) AS avg_rating,
        COUNT(*) AS rating_count
    FROM public.sportangebote_user_ratings r
    GROUP BY r.sportangebot_href
),
future_events AS (
    SELECT
        sk.offer_href AS href,
        COUNT(*) FILTER (
            WHERE kt.start_time >= now()
              AND kt.canceled = false
        ) AS future_events_count
    FROM public.sportkurse sk
    JOIN public.kurs_termine kt
      ON kt.kursnr = sk.kursnr
    GROUP BY sk.offer_href
),
offer_trainers AS (
    SELECT
        sk.offer_href AS href,
        jsonb_agg(
            DISTINCT jsonb_build_object(
                'name',   t.name,
                'rating', t.rating
            )
        ) AS trainers
    FROM public.sportkurse sk
    JOIN public.kurs_trainer kt
      ON kt.kursnr = sk.kursnr
    JOIN public.trainer t
      ON t.name = kt.trainer_name
    GROUP BY sk.offer_href
)
SELECT
    sa.href,
    sa.name,
    sa.description,
    sa.intensity,
    sa.focus,
    sa.setting,
    sa.icon,
    sa.image_url,

    COALESCE(r.avg_rating, 0)::numeric(4,2) AS avg_rating,
    COALESCE(r.rating_count, 0)              AS rating_count,
    COALESCE(fe.future_events_count, 0)      AS future_events_count,
    COALESCE(ot.trainers, '[]'::jsonb)       AS trainers
FROM public.sportangebote sa
LEFT JOIN ratings        r  ON r.href  = sa.href
LEFT JOIN future_events  fe ON fe.href = sa.href
LEFT JOIN offer_trainers ot ON ot.href = sa.href;

-- 6.3 vw_termine_full

CREATE OR REPLACE VIEW public.vw_termine_full AS
WITH trainer_per_course AS (
    SELECT
        kt.kursnr,
        jsonb_agg(
            DISTINCT jsonb_build_object(
                'name',   t.name,
                'rating', t.rating
            )
        ) AS trainers
    FROM public.kurs_trainer kt
    JOIN public.trainer t
      ON t.name = kt.trainer_name
    GROUP BY kt.kursnr
)
SELECT
    kt.kursnr,
    sk.offer_href,
    sa.name AS sport_name,
    kt.location_name,
    kt.start_time,
    kt.end_time,
    kt.canceled,
    COALESCE(tpc.trainers, '[]'::jsonb) AS trainers
FROM public.kurs_termine kt
JOIN public.sportkurse sk
  ON sk.kursnr = kt.kursnr
JOIN public.sportangebote sa
  ON sa.href = sk.offer_href
LEFT JOIN trainer_per_course tpc
  ON tpc.kursnr = kt.kursnr;

-- Parts of this codebase were developed with the assistance of AI-based tools (Cursor and Github Copilot)
-- All outputs generated by such systems were reviewed, validated, and modified by the author.