"""Utility modules for UnisportAI application.

This package contains helper functions extracted from streamlit_app.py
to organize code better and make it easier to reuse functions.

WHAT IS THIS PACKAGE?
In Python, a package is a folder with an __init__.py file
This file makes Python treat the folder as a package that can be imported
Instead of having all code in one huge file (streamlit_app.py), the code is split
into smaller modules that each have a specific purpose:

db.py: Functions for talking to the database (reading and writing data to Supabase)
auth.py: Functions for user login, logout, and checking if someone is logged in
user.py: Functions for managing user profiles, favorites, and preferences
filters.py: Functions for filtering events and offers based on user criteria
ml_utils.py: Functions for machine learning recommendations
formatting.py: Functions for formatting HTML and creating nice looking cards

WHY WAS THIS PACKAGE CREATED?
There are several benefits of organizing code this way:

1. Better organization: Functions that do similar things are grouped together
   For example, all database functions are in db.py, not scattered everywhere

2. Easier to find code: When a function that filters events is needed, it can be found
   in filters.py. This avoids searching through thousands of lines

3. Reusability: These functions can be imported and used in multiple places
   For example, filter_events() can be used in different parts of the app

4. Maintainability: When filtering logic needs to be changed, only
   filters.py needs to be edited. Changes to one module don't break other modules

HOW TO USE THIS PACKAGE?
Functions can be imported in different ways:

    # Import specific functions from the package
    from utils import filter_events
    
    # Import functions from a specific module
    from utils.db import get_offers_complete
    from utils.auth import is_logged_in

The __all__ list at the bottom defines which functions are "public"
When someone does "from utils import *", only the functions in __all__ are imported
This is a best practice: it controls what other code can access
"""

# Import functions from different modules so they're available when someone imports utils
# The dot (.) means "from the current package"
# Relative imports (with .) are preferred over absolute imports in packages

# Database functions
from .db import get_data_timestamp

# Machine learning functions
from .ml_utils import load_knn_model, build_user_preferences_from_filters, get_ml_recommendations

# Filtering functions
from .filters import check_event_matches_filters, filter_offers, filter_events

# Formatting functions
from .formatting import create_user_info_card_html

# This list defines what gets imported when someone does "from utils import *"
# __all__ is a special variable that Python looks for
# It's a way to control what's "public" vs "private" in this package
# Only the functions listed here will be imported with "import *"
__all__ = [
    'get_data_timestamp',
    'load_knn_model',
    'build_user_preferences_from_filters',
    'get_ml_recommendations',
    'check_event_matches_filters',
    'filter_offers',
    'filter_events',
    'create_user_info_card_html',
]

# Parts of this codebase were developed with the assistance of AI-based tools (Cursor and Github Copilot)
# All outputs generated by such systems were reviewed, validated, and modified by the author.
