"""
================================================================================
UTILS PACKAGE
================================================================================

Purpose: Utility modules for UnisportAI application. Contains helper functions
extracted from streamlit_app.py to organize code better and make it easier to reuse functions.

MODULES:
- db.py: Functions for database access (reading and writing data to Supabase)
- auth.py: Functions for user login, logout, and authentication
- filters.py: Functions for filtering events and offers based on user criteria
- ml_utils.py: Functions for machine learning recommendations
- formatting.py: Functions for formatting HTML and creating display elements
- analytics.py: Functions for analytics visualizations

WHY: Better organization, easier to find code, reusability, maintainability.
================================================================================
"""

# =============================================================================
# IMPORTS
# =============================================================================
# PURPOSE: Import functions from different modules so they're available when someone imports utils
# WHY: The dot (.) means "from the current package". Relative imports are preferred
#      over absolute imports in packages.

# Machine learning functions
from .ml_utils import (
    load_knn_model,
    build_user_preferences_from_filters
)

# Filtering functions
from .filters import (
    filter_offers,
    filter_events,
    get_filter_values_from_session,
    has_event_filters,
    has_offer_filters,
    initialize_session_state,
    apply_soft_filters_to_score,
    get_merged_recommendations,
    apply_ml_recommendations_to_offers
)

# Formatting functions
from .formatting import (
    format_intensity_display,
    format_focus_display,
    format_setting_display,
    format_trainers_display,
    create_offer_metadata_df,
    parse_event_datetime,
    format_weekday,
    format_time_range,
    get_match_score_style,
    render_user_avatar,
    convert_events_to_table_data
)

# Analytics functions
from .analytics import render_analytics_section, render_team_contribution_matrix

# Database loading and filtering functions
from .db import (
    load_and_filter_offers,
    load_and_filter_events
)

# =============================================================================
# PUBLIC API
# =============================================================================
# PURPOSE: Define which functions are "public" (available via "from utils import *")
# WHY: __all__ is a special variable that Python looks for. It's a way to control
#      what's "public" vs "private" in this package. Only the functions listed here
#      will be imported with "import *". This is a best practice.

__all__ = [
    'load_knn_model',
    'build_user_preferences_from_filters',
    'filter_offers',
    'filter_events',
    'get_filter_values_from_session',
    'has_event_filters',
    'has_offer_filters',
    'apply_soft_filters_to_score',
    'get_merged_recommendations',
    'apply_ml_recommendations_to_offers',
    'format_intensity_display',
    'format_focus_display',
    'format_setting_display',
    'format_trainers_display',
    'create_offer_metadata_df',
    'parse_event_datetime',
    'format_weekday',
    'format_time_range',
    'get_match_score_style',
    'render_user_avatar',
    'convert_events_to_table_data',
    'initialize_session_state',
    'render_analytics_section',
    'render_team_contribution_matrix',
    'load_and_filter_offers',
    'load_and_filter_events',
]

# Parts of this codebase were developed with the assistance of AI-based tools (Cursor and Github Copilot)
# All outputs generated by such systems were reviewed, validated, and modified by the author.
