"""
================================================================================
UTILS PACKAGE
================================================================================

Purpose: Utility modules for UnisportAI application. Contains helper functions
extracted from streamlit_app.py to organize code better and make it easier to reuse functions.

MODULES:
- db.py: Functions for database access (reading and writing data to Supabase)
- auth.py: Functions for user login, logout, and authentication
- filters.py: Functions for filtering events and offers based on user criteria
- ml_utils.py: Functions for machine learning recommendations
- formatting.py: Functions for formatting HTML and creating display elements
- analytics.py: Functions for analytics visualizations

IMPORT STYLE:
This package uses explicit imports for better clarity and maintainability.
Import directly from modules: `from utils.filters import filter_events`
This makes it immediately clear which module each function comes from.

WHY: Better organization, easier to find code, reusability, maintainability.
================================================================================
"""

# Parts of this codebase were developed with the assistance of AI-based tools (Cursor and Github Copilot)
# All outputs generated by such systems were reviewed, validated, and modified by the author.
