"""HTML and formatting utilities.

This module provides functions for generating HTML and formatted strings that
can be displayed in Streamlit using st.markdown() with unsafe_allow_html=True.

WHAT IS THIS MODULE FOR?
-------------------------
Streamlit has built-in components (st.write, st.title, etc.), but sometimes
you need custom styling. This module helps create custom HTML/CSS that can
be rendered in Streamlit.

IMPORTANT FOR BEGINNERS:
------------------------
- HTML (HyperText Markup Language) is the language used to structure web pages
- CSS (Cascading Style Sheets) is used to style HTML elements
- Streamlit normally handles styling automatically, but you can override it
- Always use unsafe_allow_html=True carefully - only with trusted content

EXAMPLE USAGE:
--------------
    html = create_user_info_card_html("John Doe", "john@example.com")
    st.markdown(html, unsafe_allow_html=True)
"""


def create_user_info_card_html(user_name, user_email):
    """
    Create HTML for a styled user information card.
    
    This function creates a gradient-styled card that displays
    user information (name and email) in the Streamlit sidebar or main area.
    
    How it works:
    1. Takes user name and email as input
    2. Builds an HTML string with inline CSS styling
    3. Returns the HTML string (which can then be rendered with st.markdown)
    
    Streamlit concept:
    Streamlit's st.markdown() can render HTML if unsafe_allow_html=True is set.
    This allows custom styling beyond Streamlit's default components.
    
    CSS explanation:
    - `background: linear-gradient(...)`: Creates a gradient color background
    - `padding: 20px`: Adds space inside the card (20 pixels on all sides)
    - `border-radius: 12px`: Makes corners rounded (12 pixel radius)
    - `box-shadow: ...`: Adds a shadow effect to make the card appear elevated
    - `color: white`: Sets text color to white
    - `font-size`, `font-weight`: Controls text appearance
    
    Example:
    ```python
    # In your Streamlit app:
    html = create_user_info_card_html("Alice Smith", "alice@example.com")
    st.markdown(html, unsafe_allow_html=True)
    ```
    
    This will display a purple gradient card showing:
    👤 Signed in as
    Alice Smith
    alice@example.com
    
    Args:
        user_name: The user's display name (e.g., "John Doe")
        user_email: The user's email address (e.g., "john@example.com")
    
    Returns:
        A complete HTML string with inline CSS that can be rendered in Streamlit
    
    Note:
        The HTML uses inline styles (style="...") which is simpler but less
        maintainable than external CSS. For production apps, consider using
        external stylesheets, but for simple cases like this, inline is fine.
    """
    # Streamlit sanitizes HTML unless unsafe_allow_html=True
    # Only trusted strings from this helper are rendered, which is why the markup is centralized
    
    # Build outer container style
    outer_style = (
        "background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); "
        "padding: 20px; "
        "border-radius: 12px; "
        "margin-bottom: 16px; "
        "box-shadow: 0 4px 6px rgba(0,0,0,0.1);"
    )
    
    # Build header style
    header_style = (
        "color: white; "
        "font-size: 14px; "
        "font-weight: 600; "
        "margin-bottom: 8px;"
    )
    
    # Build name style
    name_style = (
        "color: white; "
        "font-size: 16px; "
        "font-weight: 700; "
        "margin-bottom: 4px;"
    )
    
    # Build email style
    email_style = (
        "color: rgba(255,255,255,0.8); "
        "font-size: 13px;"
    )
    
    # Build HTML string
    html = f"""
    <div style="{outer_style}">
        <div style="{header_style}">
            👤 Signed in as
        </div>
        <div style="{name_style}">
            {user_name}
        </div>
        <div style="{email_style}">
            {user_email}
        </div>
    </div>
    """

    return html

# Parts of this codebase were developed with the assistance of AI-based tools (Cursor and Github Copilot)
# All outputs generated by such systems were reviewed, validated, and modified by the author.
